### ISSUE TITLE
Too dumb.  Also error on line 57

### ISSUE THREAD

**Issue by blucia0a** [dbalatero/horse#2]
There was one fucking rule.
Don't pet the horses
Now you lose all your money except $0.01
You currently have $0.01
-------------------------
./horse:57:in `eval': (eval):1: Can't escape from eval with next (SyntaxError)

**Comment by ohwillie** [comment]
addressed in https://github.com/dbalatero/horse/commit/3ab8f2291289db36e1a03b99cefbc9e3abf568b7
